JobProject/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('jobs/', include('jobs.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
]

jobs/urls.py
from django.urls import path
from jobs import views

app_name = 'jobs'

urlpatterns = [
    path('', views.JobView.as_view(), name='list_jobs'),
    path('new/', views.CreateJobView.as_view(), name='create_job'),
    path('<int:pk>/edit/', views.UpdateJobView.as_view(), name='edit_job'),
    path('<int:pk>/activate/', views.activate, name='activate'),
    path('<int:pk>/deactivate/', views.deactivate, name='deactivate'),
    path('<int:pk>/delete', views.DeleteJobView.as_view(), name='delete'),
]

jobs/models.py
from django.db import models


# Create your models here.
class Job(models.Model):
    url = models.CharField(max_length=100)
    title = models.CharField(max_length=100)
    description = models.TextField()
    active = models.BooleanField(default=1)

    def __str__(self):
        return f'url: {self.url} | title: {self.title} | description: {self.description}'

jobs/views.py
import time
from django.contrib.auth.decorators import login_required
from django.forms import TextInput
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from jobs.models import Job


# Create your views here.
class JobView(ListView):
    model = Job
    template_name = 'jobs/jobs_index.html'


class CreateJobView(CreateView):
    model = Job
    fields = ['url', 'title', 'description']
    template_name = 'jobs/jobs_form.html'

    def get_success_url(self):
        return reverse('jobs:list_jobs')


class UpdateJobView(UpdateView):
    model = Job
    fields = ['url', 'title', 'description']
    template_name = 'jobs/jobs_form_edit.html'

    def get_success_url(self):
        return reverse('jobs:list_jobs')


class DeleteJobView(DeleteView):
    model = Job
    fields = ['url', 'title', 'description']
    template_name = 'jobs/jobs_form_edit.html'

    def get_success_url(self):
        # reverse('jobs:delete')
        # time.sleep(3)
        return reverse('jobs:list_jobs')


def deactivate(request, pk):
    Job.objects.filter(id=pk).update(active=0)
    return redirect('jobs:list_jobs')


def activate(request, pk):
    Job.objects.filter(id=pk).update(active=1)
    return redirect('jobs:list_jobs')


def website(request, url):
    return redirect(url)

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    {% block title %}
    {% endblock %}
    <link rel="stylesheet" href="{% static 'templates/dist/output.css' %}">
</head>
<body class="bg-black text-white font-poppins">
<nav
        class="w-full flex bg-indigo-600 fixed z-10 h-12 justify-center gap-60 items-center text-lg font-medium top-0 "
>
    <a href="{% url 'jobs:list_jobs' %}" >SEE ALL JOBS</a>
    <a href="{% url 'jobs:create_job' %}" >POST A JOB</a>
</nav>



{% block content %}
{% endblock %}


<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.11.4/gsap.min.js" integrity="sha512-f8mwTB+Bs8a5c46DEm7HQLcJuHMBaH/UFlcgyetMqqkvTcYg4g5VXsYR71b3qC82lZytjNYvBj2pf0VekA9/FQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.11.4/ScrollTrigger.min.js" integrity="sha512-A64Nik4Ql7/W/PJk2RNOmVyC/Chobn5TY08CiKEX50Sdw+33WTOpPJ/63bfWPl0hxiRv1trPs5prKO8CpA7VNQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

{#<script>#}
{##}
{#    let tl = gsap.timeline({ defaults: { ease: "power4.inOut", duration: 1}});#}
{#    tl.to('#job-container', { opacity: 1,  duration: 1 })#}
{#</script>#}
</body>
</html>

templates/jobs/jobs_form.html
{% extends 'base.html' %}

{% block content %}


    <form method="post" class="flex flex-col mx-auto justify-center items-center w-2/6 ">
        {% csrf_token %}
        <div class="flex flex-col justify-center items-center border border-indigo-500 py-20 px-20 ">
            {% block button %}
            {% endblock %}

            {% for field in form %}
                {{ field.label }}
                <div class="text-black">{{ field }} </div>{{ field.errors }} <br>
            {% endfor %}
            <button type="submit" class="flex mx-auto justify-center bg-indigo-700 py-2 w-2/6  text-xl font-bold ">
                SUBMIT
            </button>
        </div>
    </form>

{% endblock %}

templates/jobs/jobs_form_edit.html
{% extends 'jobs/jobs_form.html' %}
{% block button %}

    <button type="submit"
            class="flex mx-auto justify-center bg-red-600 py-2 w-2/3  text-xl font-bold mb-10">
        <a href="{% url 'jobs:delete' job.id %}">DELETE</a>
    </button>

{% endblock %}

templates/jobs/jobs_index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    {% for item in job_list %}

        <div class="relative" id="job-container" >
            <div
                    class="absolute w-2/3 mx-auto inset-0 bg-violet-600 rounded-2xl blur-md"></div>
            <div class="flex flex-col relative bg-slate-900 w-2/3 mx-auto my-20 rounded-2xl space-y-3 p-9" >

                <span class="relative flex flex-row text-3xl font-medium gap-5">
                    {{ item.title }}
                    <div class="flex justify-between w-full h-full flex-1">
                    <a href="{% url 'jobs:edit_job' item.id %}"><img src="{% static 'assets/edit.svg' %}"
                                                                     class="scale-90"
                                                                     alt="edit"
                                                                     href="{% url 'jobs:edit_job' item.id %}"/></a>
                        {% if not item.active %}
                            <button class="text-xl  py-2 px-5 bg-red-600 transition duration-150 ease-in-out hover:bg-red-500  hover:scale-110  "><a href="{% url 'jobs:activate' item.id %}">Activate</a></button>
                        {% else %}
                            <button class="text-xl py-2 px-5 bg-green-600 transition duration-150 ease-in-out hover:bg-green-500 hover:scale-110 "><a href="{% url 'jobs:deactivate' item.id %}">Deactivate</a></button>
                        {% endif %}
                        </div>
                </span>

                {% if item.active %}
                    <div class="text-xl text-green-500">Active</div>
                {% else %}
                    <div class="text-xl text-red-500">Not active</div>
                {% endif %}

                <a href="http://{{ item.url }}" onclick="" class="text-indigo-300">{{ item.url }}</a>
                <span class="text-gray-200 leading-7">{{ item.description }}</span>



            </div>
        </div>

    {% endfor %}

{% endblock %}

templates/jobs/jobs_succesfully.html
{% extends 'base.html' %}
{% block content %}
    <span class="text-9xl">Succesfully deleted!</span>
    <span class="text-xl">Redirecting to home in ..<span id="countdown">3</span> </span>
    <script>
        let count = 3;
        function countdown() {
            count--;
            if(count > 0) {
                document.getElementById("countdown").innerHTML=count;
                setTimeout(countdown, 1000);
            }
        }
        countdown();
    </script>
{% endblock %}